---
version: '3.7'
services:
  app:
    image: caddy:2.1.1-alpine
    networks:
      - local
  proxy:
    image: nginx-proxy:latest
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "./example/app.conf:/etc/nginx/app.conf"
    depends_on:
      - app
    networks:
      - local
  jaeger:
    image: jaegertracing/all-in-one:1.53
    ports:
      - "16686:16686"
    networks:
      - local
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.92.0
    command:
      - "--config=/etc/otel-collector/config.yml"
    volumes:
      - "./example/otel-collector-config.yml:/etc/otel-collector/config.yml"
    networks:
      - local

networks:
  local:
